package com.aiaffiliate.domain.model;

/** 页面信任增强元素。 */
public enum TrustElement { PROS_AND_CONS, PRICE_RANGE, SELLER_RATING, REVIEW_COUNT, SELECTION_CRITERIA, METHODOLOGY, AFFILIATE_DISCLOSURE, FAQ, AUTHOR_NOTE, LAST_UPDATED_DATE, UNKNOWN }
